[
  {
    "id": "maerki-gpt",
    "name": "Märki",
    "emoji": "🧠",
    "description": "Strategie & Lifecycle",
    "deployment": "maerki-gpt",
    "prompt": "prompts/maerki-gpt.md",
    "yaml": "store/maerki-gpt.yaml",
    "testable": true,
    "free": true,
    "public": true,
    "custom": true
  },
  {
    "id": "kaija-gpt",
    "name": "KaiJa",
    "emoji": "📣",
    "description": "Marketing & Funnel",
    "deployment": "kaija-gpt",
    "prompt": "prompts/kaija-gpt.md",
    "yaml": "store/kaija-gpt.yaml",
    "testable": true,
    "free": false,
    "public": true,
    "custom": true
  },
  {
    "id": "honey-gpt",
    "name": "Honey",
    "emoji": "💸",
    "description": "Pricing & Monetarisierung",
    "deployment": "honey-gpt",
    "prompt": "prompts/honey-gpt.md",
    "yaml": "store/honey-gpt.yaml",
    "testable": true,
    "free": false,
    "public": true,
    "custom": true
  },
  {
    "id": "homie-gpt",
    "name": "Homie",
    "emoji": "🎓",
    "description": "Onboarding & Lernen",
    "deployment": "homie-gpt",
    "prompt": "prompts/homie-gpt.md",
    "yaml": "store/homie-gpt.yaml",
    "testable": true,
    "free": false,
    "public": true,
    "custom": true
  },
  {
    "id": "kaivio-gpt",
    "name": "KaiVio",
    "emoji": "💼",
    "description": "Karriere & Bewerbung",
    "deployment": "kaivio-gpt",
    "prompt": "prompts/kaivio-gpt.md",
    "yaml": "store/kaivio-gpt.yaml",
    "testable": true,
    "free": false,
    "public": true,
    "custom": true
  },
  {
    "id": "soulguide-gabriela-gpt",
    "name": "Gabriela",
    "emoji": "🌿",
    "description": "Ethik & Achtsamkeit",
    "deployment": "soulguide-gabriela-gpt",
    "prompt": "prompts/soulguide-gabriela-gpt.md",
    "yaml": "store/soulguide-gabriela-gpt.yaml",
    "testable": true,
    "free": false,
    "public": true,
    "custom": true
  },
  {
    "id": "soulsyncai-gpt",
    "name": "SoulSync AI",
    "emoji": "🌀",
    "description": "Human Design Coaching",
    "deployment": "soulsyncai-gpt",
    "prompt": "prompts/soulsyncai-gpt.md",
    "yaml": "store/soulsyncai-gpt.yaml",
    "testable": true,
    "free": false,
    "public": true,
    "custom": true
  },
  {
    "id": "baschis-gpt",
    "name": "Baschi",
    "emoji": "🤝",
    "description": "LinkedIn Sales & Pitching",
    "deployment": "baschis-gpt",
    "prompt": "prompts/baschis-gpt.md",
    "yaml": "store/baschis-gpt.yaml",
    "testable": true,
    "free": false,
    "public": true,
    "custom": true
  },
  {
    "id": "dailyjasmin-gpt",
    "name": "DailyJasmin",
    "emoji": "🌸",
    "description": "Selfcare & Tagesimpulse",
    "deployment": "dailyjasmin-gpt",
    "prompt": "prompts/dailyjasmin-gpt.md",
    "yaml": "store/dailyjasmin-gpt.yaml",
    "testable": true,
    "free": false,
    "public": true,
    "custom": true
  },
  {
    "id": "_fallback",
    "name": "Fallback",
    "emoji": "🛡️",
    "description": "Fehlermeldung & Support-Hinweis",
    "deployment": "default-gpt",
    "prompt": "prompts/fallback.md",
    "yaml": "store/fallback.yaml",
    "testable": false,
    "free": true,
    "public": false,
    "custom": false
  }
]
